### ISSUE TITLE
ValueError: invalid literal for int() with base 10: with wiki bin

### ISSUE THREAD

**Issue by drophit** [Conchylicultor/DeepQA#101]
Trying out the wiki.bin - gettin this

`D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot>python main.py --initEmbeddings --embeddingSource=wiki.en.bin
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.1.0
Loading dataset from D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\data/samples/dataset-cornell-length10-filter1-vocabSize40000.pkl
Loaded cornell: 24643 words, 159653 QA
Model creation...
2017-04-23 20:38:53.299789: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.300319: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305156: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305278: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305385: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305482: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305598: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:53.305704: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-04-23 20:38:54.052872: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties:
name: GeForce GTX 780M
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.34GiB
2017-04-23 20:38:54.052994: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:908] DMA: 0
2017-04-23 20:38:54.057722: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:918] 0:   Y
2017-04-23 20:38:54.058173: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 780M, pci bus id: 0000:01:00.0)
Initialize variables...
WARNING: No previous model found, starting from clean directory: D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\save/model
Loading pre-trained word embeddings from D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\data\embeddings\wiki.en.bin
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\chatbot.py", line 200, in main
    self.loadEmbedding(self.sess)
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\chatbot.py", line 414, in loadEmbedding
    vocab_size, vector_size = map(int, header.split())
ValueError: invalid literal for int() with base 10: b',\x01\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x80\x84\x1e\x00\x03\x00\x00\x00\x06\x00\x00\x00d\x00\x00\x00-C\x1c\xeb\x`

**Comment by dongniu0927** [comment]
Got the same problem, anybody knows why?
