### ISSUE TITLE
Permissions error with scotus

### ISSUE THREAD

**Issue by drophit** [Conchylicultor/DeepQA#102]
D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot>python main.py --corpus=scotus --modelTag=scotus
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.1.0
Training samples not found. Creating dataset...
Constructing full dataset...
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\chatbot.py", line 158, in main
    self.textData = TextData(self.args)
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\textdata.py", line 97, in __init__
    self.loadCorpus()
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\textdata.py", line 260, in loadCorpus
    corpusData = TextData.availableCorpus[self.args.corpus](self.corpusDir + optional)
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\corpus\scotusdata.py", line 35, in __init__
    self.lines = self.loadLines(os.path.join(dirName, "scotus"))
  File "D:\drophit\Documents\TensorFlowChatBots\3.5PythonTensor1.0-DeepQABot\chatbot\corpus\scotusdata.py", line 48, in loadLines
    with open(fileName, 'r') as f:
PermissionError: [Errno 13] Permission denied: 'D:\\drophit\\Documents\\TensorFlowChatBots\\3.5PythonTensor1.0-DeepQABot\\data\\scotus\\scotus'

**Comment by EMCP** [comment]
again, this is perhaps a path issue since you're in Windows.. try my PR and see if the error occurs

https://github.com/Conchylicultor/DeepQA/pull/144
