### ISSUE TITLE
how to get the answer and use it in other places in the script

### ISSUE THREAD

**Issue by cxnlpsdw** [Conchylicultor/DeepQA#105]
If I want to use the answer from the model and process it in my script, such as:

bot = chatbot.Chatbot()
answer = bot.getAnswer("hello")
use_answer_to_do_sth...

what should I do?

I've tried to use the singlePredict(question) to get the answer, but I got the following message:
Traceback (most recent call last):
  File "/DeepQA-master/test.py", line 5, in <module>
    bot.initialize()
  File "/DeepQA-master/chatbot/chatbot.py", line 703, in initialize
    self.mainTestInteractive(self.sess)
  File "/DeepQA-master/chatbot/chatbot.py", line 333, in mainTestInteractive
    answer = self.singlePredict(question, questionSeq)
  File "/DeepQA-master/chatbot/chatbot.py", line 366, in singlePredict
    answer = self.textData.deco2sentence(output)
  File "/DeepQA-master/chatbot/textdata.py", line 612, in deco2sentence
    for out in decoderOutputs:
TypeError: 'NoneType' object is not iterable

**Comment by Conchylicultor** [comment]
You have to launch the chatbot with the `--test deamon` flag. See the website code for an example:
https://github.com/Conchylicultor/DeepQA/blob/master/chatbot_website/chatbot_interface/chatbotmanager.py#L41
