### ISSUE TITLE
ModuleNotFoundError: No module named 'chatbot.textdata'; 'chatbot' is not a package

### ISSUE THREAD

**Issue by Mrinal18** [Conchylicultor/DeepQA#125]
hey, i am not able to solve this error just after training

eloaded modules: chatbot, chatbot.chatbot, chatbot.textdata, chatbot.corpus.cornelldata, chatbot.corpus.opensubsdata, chatbot.corpus.scotusdata, chatbot.corpus.ubuntudata, chatbot.corpus.lightweightdata, chatbot.model
Traceback (most recent call last):

  File "<ipython-input-7-64afdda41758>", line 1, in <module>
    runfile('/home/bizviz/DeepQA/chatbot/chatbot.py', wdir='/home/bizviz/DeepQA/chatbot')

  File "/home/bizviz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/bizviz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/bizviz/DeepQA/chatbot/chatbot.py", line 33, in <module>
    from chatbot.textdata import TextData

  File "/home/bizviz/DeepQA/chatbot/chatbot.py", line 33, in <module>
    from chatbot.textdata import TextData

ModuleNotFoundError: No module named 'chatbot.textdata'; 'chatbot' is not a package

**Comment by BobCN2017** [comment]
I meet the similar problem.I solve it by add the below sentences before line 33.
import sys
sys.path.append('D:/DeepQA/chatbot')

you can try it.remember modify the directory for yourself.

**Comment by shre81** [comment]
This is a Py36 issue. I was able to resolve by switching to Py35.

**Comment by wujiajia2017scnu** [comment]
change the name of chatbot.py into chatbot1.py
because  the package and chatbot.py ,do not have the same name
