### ISSUE TITLE
got an unexpected keyword argument 'websocket_handshake_timeout'

### ISSUE THREAD

**Issue by GYXie** [Conchylicultor/DeepQA#127]
When I tried to run the website, I got the following error:

> Initializing bot...
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.2.0
Loading dataset from /Users/xgy/Documents/workspace/DeepQA/data/samples/dataset-cornell-length10-filter1-vocabSize40000.pkl
Loaded cornell: 24643 words, 159657 QA
Model creation...
2017-06-17 03:29:05.357589: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-17 03:29:05.357622: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-17 03:29:05.357631: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-17 03:29:05.357638: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: No previous model found, starting from clean directory: /Users/xgy/Documents/workspace/DeepQA/save/model-server
Daemon mode, running in background...
Performing system checks...

System check identified no issues (0 silenced).
June 17, 2017 - 03:29:06
Django version 1.11.2, using settings 'chatbot_website.settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
2017-06-17 03:29:06,054 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-17 03:29:06,055 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-17 03:29:06,056 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-17 03:29:06,057 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1183da1e0>
Traceback (most recent call last):
  File "/Users/xgy/anaconda/envs/envpy3/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/xgy/anaconda/envs/envpy3/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 98, in inner_run
    websocket_handshake_timeout=self.websocket_handshake_timeout,
TypeError: __init__() got an unexpected keyword argument 'websocket_handshake_timeout'

I don't know how to fix it.

**Comment by Conchylicultor** [comment]
Not sure what's happening but I'll guess it's a problem with a version of `channels`.
