### ISSUE TITLE
Failed to use model-pretrainedv2

### ISSUE THREAD

**Issue by huqingzhou** [Conchylicultor/DeepQA#140]
WARNING: Restoring previous model from /home/centos/DeepQA/save/model-pretrainedv2/model.ckpt
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "embedding_rnn_seq2seq/rnn/embedding_wrapper/multi_rnn_cell/cell_1/basic_lstm_cell/kernel" not found in checkpoint files /home/centos/DeepQA/save/model-pretrainedv2/model.ckpt
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]

During handling of the above exception, another exception occurred:

**Comment by EMCP** [comment]
I'm guessing you are running the correct version of TensorFlow?? , I think it needs to be below 1.2..

I got the same error after running it in v1.2.1 with the script translating the keywords

**Comment by nichcuta** [comment]
[Models](https://mcastedu-my.sharepoint.com/personal/nicholas_cutajar_a100636_mcast_edu_mt/Documents/Forms/All.aspx?slrid=f77d239e%2D708b%2D4000%2D817c%2D7f985743c779&RootFolder=%2Fpersonal%2Fnicholas%5Fcutajar%5Fa100636%5Fmcast%5Fedu%5Fmt%2FDocuments%2FDeepQA%20%2D%20Pre%20Trained%20Models&FolderCTID=0x012000ACF25C8BFBFE2F4A85CE16FF1E3C2BBC) updated and trained with tf1.3

**Comment by adamknaze** [comment]
@nichcuta the link is broken (authorization required)

**Comment by nichcuta** [comment]
[Updated Link](https://mcastedu-my.sharepoint.com/:f:/g/personal/nicholas_cutajar_a100636_mcast_edu_mt/EkxsV3eF-UJGqWj2eQk4D0UBW3YlYw-R_ZH-ZYGkjV4BRg?e=tjS0hX) Should be working again now.

**Comment by ondev** [comment]
> [Updated Link](https://mcastedu-my.sharepoint.com/:f:/g/personal/nicholas_cutajar_a100636_mcast_edu_mt/EkxsV3eF-UJGqWj2eQk4D0UBW3YlYw-R_ZH-ZYGkjV4BRg?e=tjS0hX) Should be working again now.

Can't download the Models now.
