### ISSUE TITLE
Failed to use pre-train model

### ISSUE THREAD

**Issue by fendouai** [Conchylicultor/DeepQA#145]
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.2.1

Warning: Restoring parameters:
globStep: 32000
watsonMode: False
autoEncode: False
corpus: cornell
datasetTag: old
maxLength: 10
filterVocab: 0
skipLines: False
vocabularySize: 0
hiddenSize: 512
numLayers: 2
softmaxSamples: 0
initEmbeddings: False
embeddingSize: 64
embeddingSource: None

Loading dataset from /home/bigdata/PycharmProjects/DeepQA/data/samples/dataset-cornell-old-length10-filter0-vocabSize0.pkl
Loaded cornell: 36901 words, 164169 QA
Model creation...
2017-09-05 14:33:31.591380: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 14:33:31.591401: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 14:33:31.591407: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 14:33:31.591422: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 14:33:31.591427: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: Restoring previous model from /home/bigdata/PycharmProjects/DeepQA/save/model-pretrainedv2/model.ckpt
Traceback (most recent call last):
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/multi_rnn_cell/cell_0/basic_lstm_cell/bias" not found in checkpoint files /home/bigdata/PycharmProjects/DeepQA/save/model-pretrainedv2/model.ckpt
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/bigdata/PycharmProjects/DeepQA/chatbot/chatbot.py", line 196, in main
    self.managePreviousModel(self.sess)
  File "/home/bigdata/PycharmProjects/DeepQA/chatbot/chatbot.py", line 479, in managePreviousModel
    self.saver.restore(sess, modelName)  # Will crash when --reset is not activated and the model has not been saved yet
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/multi_rnn_cell/cell_0/basic_lstm_cell/bias" not found in checkpoint files /home/bigdata/PycharmProjects/DeepQA/save/model-pretrainedv2/model.ckpt
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

Caused by op 'save/RestoreV2_3', defined at:
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/bigdata/PycharmProjects/DeepQA/chatbot/chatbot.py", line 174, in main
    self.saver = tf.train.Saver(max_to_keep=200)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/bigdata/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/multi_rnn_cell/cell_0/basic_lstm_cell/bias" not found in checkpoint files /home/bigdata/PycharmProjects/DeepQA/save/model-pretrainedv2/model.ckpt
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

**Comment by EMCP** [comment]
Please, for readability add backticks to your console output

https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by EMCP** [comment]
```
"embedding_rnn_seq2seq/embedding_rnn_decoder/rnn_decoder/output_projection_wrapper/multi_rnn_cell/cell_0/basic_lstm_cell/bias" not found in checkpoint files /home/bigdata/PycharmProjects/DeepQA/save/model-pretrainedv2/model.ckpt
```

Based on this.. you're using TF 1.3 .. but the pretrained model uses an older version of tensorflow.. I got this same error, it's due to some name changes in their models/apis.. you can attempt to update a pre-trained model using a script.. I couldn't get it to work but maybe you could...

https://github.com/Conchylicultor/DeepQA/issues/120#issuecomment-321695344

**Comment by fendouai** [comment]
Thanks,I have solved this issue.

**Comment by Hexagram-King** [comment]
@fendouai  How did you solve the issue? Attempt to receive your solution~~
