### ISSUE TITLE
Not able to run main.py!! Have updated cuda as well...please help.

### ISSUE THREAD

**Issue by sathish96** [Conchylicultor/DeepQA#172]
python main.py
when i run main.py i get these errors....i'm relatively new to this, kindly help :)
Traceback (most recent call last):
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from chatbot import chatbot
  File "C:\Users\Sathish\Desktop\chatbot\chatbot\chatbot.py", line 26, in <module>
    import tensorflow as tf
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\Sathish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

**Comment by cvmk95** [comment]
make sure you are using tf 1.1.0 with cuda 8 and cudnn 5.
