### ISSUE TITLE
KeyError: 'CHATBOT_SECRET_KEY'

### ISSUE THREAD

**Issue by GirishBB** [Conchylicultor/DeepQA#179]
when i run "python manage.py makemigrations"
It thows an KeyError:  'CHATBOT_SECRET_KEY'

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\girish\DeepQA-master\chatbot_website\chatbot_website\settings.py", line 23, in <module>
    SECRET_KEY = os.environ['CHATBOT_SECRET_KEY']
  File "C:\Users\girish\Anaconda3\envs\my_env\lib\os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'CHATBOT_SECRET_KEY'

Can someone help me out with this error?

**Comment by proszx** [comment]
if u R in linux **export CHATBOT_SECRET_KEY="my-secret-key"** then migrations and migrate
in windows use SET

**Comment by jackeyEllison** [comment]
> if u R in linux **export CHATBOT_SECRET_KEY="my-secret-key"** then migrations and migrate in windows use SET

I try to use "set" ,but it not work
