### ISSUE TITLE
Django Error when i run python manage.py runserver

### ISSUE THREAD

**Issue by proszx** [Conchylicultor/DeepQA#180]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f35be747ae8>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/root/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/root/anaconda3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/anaconda3/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/root/anaconda3/lib/python3.6/site-packages/channels/apps.py", line 22, in ready
    monkeypatch_django()
  File "/root/anaconda3/lib/python3.6/site-packages/channels/hacks.py", line 10, in monkeypatch_django
    from .management.commands.runserver import Command as RunserverCommand
  File "/root/anaconda3/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
ImportError: cannot import name 'build_endpoint_description_strings'

**Comment by proszx** [comment]
when I set a single Django project ,it's has no error
