### ISSUE TITLE
CommandError: You have not set ASGI_APPLICATION, which is needed to run the server.

### ISSUE THREAD

**Issue by GirishBB** [Conchylicultor/DeepQA#183]
how to solve this problem?

**Comment by glaucogoca** [comment]
I got this problem and as documentation says you need to create a variable **ASGI_APPLICATION** (http://channels.readthedocs.io/en/latest/deploying.html)

I put this line in chatbot_website/settings.py

`ASGI_APPLICATION = 'chatbot_website.wsgi.application'`

But now I got this error

```
2018-04-03 17:03:06,990 - ERROR - http_protocol - Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/daphne/http_protocol.py", line 158, in process
    "server": self.server_addr,
  File "/anaconda3/lib/python3.6/site-packages/daphne/server.py", line 184, in create_application
    application_instance = self.application(scope=scope)
  File "/anaconda3/lib/python3.6/site-packages/channels/staticfiles.py", line 42, in __call__
    return self.application(scope)
TypeError: __call__() missing 1 required positional argument: 'start_response'
```

**Comment by dfenglei** [comment]
try the below line. It works for me.
ASGI_APPLICATION = 'chatbot_website.asgi.application'

**Comment by dfenglei** [comment]
sorry for typo.
ASGI_APPLICATION = 'chatbot_website.routing.application'

**Comment by bl-deepakchawla** [comment]
django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'mysite.routing'
