### ISSUE TITLE
DeepQA 

### ISSUE THREAD

**Issue by joy213** [Conchylicultor/DeepQA#219]

**Comment by joy213** [comment]
TensorFlow detected: v2.8.0
Loading dataset from C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\data\samples\dataset-cornell-length10-filter1-vocabSize40000.pkl
Loaded cornell: 24412 words, 159733 QA
Model creation...
2022-04-03 02:43:58.103799: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-04-03 02:43:58.104135: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-03 02:43:58.109636: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-7SETT74
2022-04-03 02:43:58.110089: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-7SETT74
Traceback (most recent call last):
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\main.py", line 29, in <module>
    chatbot.main()
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\chatbot\chatbot1.py", line 170, in main
    self.model = Model(self.args, self.textData)
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\chatbot\model.py", line 105, in __init__
    self.buildNetwork()
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\chatbot\model.py", line 155, in buildNetwork
    encoDecoCell = tf.compat.v1.estimator.rnn.MultiRNNCell(
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\venv\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 59, in __getattr__
    return getattr(module, item)
  File "C:\Users\user\Documents\DEEPQA PROJECT\DeepQA-master\venv\lib\site-packages\tensorflow\python\util\module_wrapper.py", line 232, in _getattr
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow_estimator.python.estimator.api._v1.estimator' has no attribute 'rnn'
 
please help, i encounted this error when training this model. um using python 3.9, tensoflow 2.8
