### ISSUE TITLE
Update pre-trained model

### ISSUE THREAD

**Issue by dragon28** [Conchylicultor/DeepQA#60]
Hello :)

I am using the latest version of DeepQA that support tenforflow version 1 which cloned from github.

Moreover, I am using the pretrained model which downloaded from the google drive.

But I encounter the following problem:

DeepQA2/chatbot_website$ python3 manage.py runserver
Initializing bot...
Welcome to DeepQA v0.1 !

TensorFlow detected: v0.12.1
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f76f8361ae8>
Traceback (most recent call last):
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/dragon/DeepQA2/chatbot_website/chatbot_interface/chatbotmanager.py", line 31, in ready
    ChatbotManager.initBot()
  File "/home/dragon/DeepQA2/chatbot_website/chatbot_interface/chatbotmanager.py", line 41, in initBot
    ChatbotManager.bot.main(['--modelTag', 'server', '--test', 'daemon', '--rootDir', chatbotPath])
  File "/home/dragon/DeepQA2/chatbot/chatbot.py", line 152, in main
    self.loadModelParams()  # Update the self.modelDir and self.globStep, for now, not used when loading Model (but need to be called before _getSummaryName)
  File "/home/dragon/DeepQA2/chatbot/chatbot.py", line 517, in loadModelParams
    raise UserWarning('Present configuration version {0} does not match {1}. You can try manual changes on \'{2}\''.format(currentVersion, self.CONFIG_VERSION, configName))
UserWarning: Present configuration version 0.2 does not match 0.4. You can try manual changes on '/home/dragon/DeepQA2/save/model-server/params.ini'

^Cdragon@dragonPCx64:~/DeepQA2/chatbot_website$ python3 manage.py runserver
Initializing bot...
Welcome to DeepQA v0.1 !

TensorFlow detected: v0.12.1

Warning: Restoring parameters:
globStep: 290000
maxLength: 10
watsonMode: False
autoEncode: None
corpus: None
datasetTag: 
hiddenSize: 256
numLayers: 2
embeddingSize: 32
initEmbeddings: None
softmaxSamples: None

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fae4dcac730>
Traceback (most recent call last):
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dragon/.local/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/dragon/DeepQA2/chatbot_website/chatbot_interface/chatbotmanager.py", line 31, in ready
    ChatbotManager.initBot()
  File "/home/dragon/DeepQA2/chatbot_website/chatbot_interface/chatbotmanager.py", line 41, in initBot
    ChatbotManager.bot.main(['--modelTag', 'server', '--test', 'daemon', '--rootDir', chatbotPath])
  File "/home/dragon/DeepQA2/chatbot/chatbot.py", line 154, in main
    self.textData = TextData(self.args)
  File "/home/dragon/DeepQA2/chatbot/textdata.py", line 76, in __init__
    self.corpusDir = os.path.join(self.args.rootDir, 'data', self.args.corpus)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

OS: Ubuntu 16.04.1 (64 Bits)
Python: 3.5.2
PiP: 9.0.1

PiP List:

appdirs (1.4.0)
apturl (0.5.2)
asgi-redis (1.0.0)
asgiref (1.0.0)
autobahn (0.17.1)
beautifulsoup4 (4.4.1)
bleach (1.5.0)
blinker (1.3)
Brlapi (0.6.4)
channels (1.0.3)
chardet (2.3.0)
checkbox-support (0.22)
command-not-found (0.3)
constantly (15.1.0)
cryptography (1.2.3)
daphne (1.0.2)
decorator (4.0.11)
defer (1.0.6)
Django (1.10.5)
entrypoints (0.2.2)
feedparser (5.1.3)
guacamole (0.9.2)
html5lib (0.9999999)
httplib2 (0.9.1)
idna (2.0)
incremental (16.10.1)
ipykernel (4.5.2)
ipython (5.2.2)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.9.5)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.1.0)
jupyter-core (4.2.1)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
mistune (0.7.3)
msgpack-python (0.4.8)
nbconvert (5.1.1)
nbformat (4.2.0)
nltk (3.2.2)
notebook (4.3.2)
numpy (1.12.0)
oauthlib (1.0.3)
onboard (1.2.0)
packaging (16.8)
padme (1.1.1)
pandas (0.19.2)
pandocfilters (1.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (9.0.1)
plainbox (0.25)
prompt-toolkit (1.0.13)
protobuf (3.2.0)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycups (1.9.73)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.1.10)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-systemd (231)
pytz (2016.10)
pyxdg (0.25)
pyzmq (16.0.2)
qtconsole (4.2.1)
redis (2.10.5)
reportlab (3.3.0)
requests (2.9.1)
scikit-learn (0.18.1)
scipy (0.18.1)
screen-resolution-extra (0.0.0)
sessioninstaller (0.0.0)
setuptools (34.1.1)
simplegeneric (0.8.1)
six (1.10.0)
system-service (0.3)
tensorflow (0.12.1)
terminado (0.6)
testpath (0.3)
tornado (4.4.2)
tqdm (4.11.2)
traitlets (4.3.1)
Twisted (16.6.0)
txaio (2.6.0)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
zope.interface (4.3.3)

**Comment by Conchylicultor** [comment]
Yes, the pre-trained model isn't compatible with the current version. I'll try to re-train a model in the next few weeks.

**Comment by dragon28** [comment]
@Conchylicultor Thanks :) :+1:

**Comment by Conchylicultor** [comment]
[Here you go](https://drive.google.com/file/d/0Bw-phsNSkq23TXltWGlOdk9wOXc/view?usp=sharing). To launch it, just run `./main.py --modelTag pretrainedv2 --test interactive`.
