### ISSUE TITLE
When I trained my model with maxLenght=5 I'm getting error while trting to use the web interface

### ISSUE THREAD

**Issue by alanbekker** [Conchylicultor/DeepQA#64]
python3 manage.py runser                                                                                                                     ver 10.124.58.43:8889
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcurand.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library                                                                                                                      libcurand.so.8.0 locally
Initializing bot...
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.0.0
Loading dataset from /home/alan/Projects/DeepQA-master_new/data/samples/...
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use SSE3 instructions, but these are available on your machine and                                                                                                                      could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use SSE4.1 instructions, but these are available on your machine a                                                                                                                     nd could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use SSE4.2 instructions, but these are available on your machine a                                                                                                                     nd could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use AVX instructions, but these are available on your machine and                                                                                                                      could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use AVX2 instructions, but these are available on your machine and                                                                                                                      could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn'                                                                                                                     t compiled to use FMA instructions, but these are available on your machine and                                                                                                                      could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with prop                                                                                                                     erties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:4b:00.0
Total memory: 7.92GiB
Free memory: 7.32GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow devi                                                                                                                     ce (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:4b:00.0)
Initialize variables...
WARNING: Restoring previous model from /home/alan/Projects/DeepQA-master_new/sav                                                                                                                     e/model-server/model.ckpt
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires                                                                                                                      shapes of both tensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires                                                                                                                      shapes of both tensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires                                                                                                                      shapes of both tensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper                                                                                                                      at 0x7fd4b5c9b0d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/error                                                                                                                     s_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires sh                                                                                                                     apes of both tensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
         [[Node: save/RestoreV2_4/_11 = _Recv[client_terminated=false, recv_devi                                                                                                                     ce="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:                                                                                                                     0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_45_save/RestoreV2_                                                                                                                     4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alan/.local/lib/python3.5/site-packages/django/utils/autoreload.py                                                                                                                     ", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/alan/.local/lib/python3.5/site-packages/django/core/management/com                                                                                                                     mands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/alan/.local/lib/python3.5/site-packages/django/utils/autoreload.py                                                                                                                     ", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/alan/.local/lib/python3.5/site-packages/django/utils/six.py", line                                                                                                                      685, in reraise
    raise value.with_traceback(tb)
  File "/home/alan/.local/lib/python3.5/site-packages/django/utils/autoreload.py                                                                                                                     ", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/alan/.local/lib/python3.5/site-packages/django/__init__.py", line                                                                                                                      27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alan/.local/lib/python3.5/site-packages/django/apps/registry.py",                                                                                                                      line 115, in populate
    app_config.ready()
  File "/home/alan/Projects/DeepQA-master_new/chatbot_website/chatbot_interface/                                                                                                                     chatbotmanager.py", line 31, in ready
    ChatbotManager.initBot()
  File "/home/alan/Projects/DeepQA-master_new/chatbot_website/chatbot_interface/                                                                                                                     chatbotmanager.py", line 41, in initBot
    ChatbotManager.bot.main(['--modelTag', 'server', '--test', 'daemon', '--root                                                                                                                     Dir', chatbotPath])
  File "/home/alan/Projects/DeepQA-master_new/chatbot/chatbot.py", line 192, in                                                                                                                      main
    self.managePreviousModel(self.sess)
  File "/home/alan/Projects/DeepQA-master_new/chatbot/chatbot.py", line 462, in                                                                                                                      managePreviousModel
    self.saver.restore(sess, modelName)  # Will crash when --reset is not activa                                                                                                                     ted and the model has not been saved yet
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.                                                                                                                     py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires sh                                                                                                                     apes of both tensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
         [[Node: save/RestoreV2_4/_11 = _Recv[client_terminated=false, recv_devi                                                                                                                     ce="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:                                                                                                                     0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_45_save/RestoreV2_                                                                                                                     4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save/Assign_7', defined at:
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alan/.local/lib/python3.5/site-packages/django/core/management/__i                                                                                                                     nit__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/alan/.local/lib/python3.5/site-packages/django/core/management/__i                                                                                                                     nit__.py", line 330, in execute
    autoreload.check_errors(django.setup)()
  File "/home/alan/.local/lib/python3.5/site-packages/django/utils/autoreload.py                                                                                                                     ", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/alan/.local/lib/python3.5/site-packages/django/__init__.py", line                                                                                                                      27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alan/.local/lib/python3.5/site-packages/django/apps/registry.py",                                                                                                                      line 115, in populate
    app_config.ready()
  File "/home/alan/Projects/DeepQA-master_new/chatbot_website/chatbot_interface/                                                                                                                     chatbotmanager.py", line 31, in ready
    ChatbotManager.initBot()
  File "/home/alan/Projects/DeepQA-master_new/chatbot_website/chatbot_interface/                                                                                                                     chatbotmanager.py", line 41, in initBot
    ChatbotManager.bot.main(['--modelTag', 'server', '--test', 'daemon', '--root                                                                                                                     Dir', chatbotPath])
  File "/home/alan/Projects/DeepQA-master_new/chatbot/chatbot.py", line 170, in                                                                                                                      main
    self.saver = tf.train.Saver(max_to_keep=200, write_version=tf.train.SaverDef                                                                                                                     .V1)  # TODO: See GitHub for format name issue (when restoring the model)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 1051, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.                                                                                                                     py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_o                                                                                                                     ps.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_de                                                                                                                     f_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.p                                                                                                                     y", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.p                                                                                                                     y", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both t                                                                                                                     ensors to match. lhs shape= [34991,32] rhs shape= [19643,32]
         [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_                                                                                                                     seq2seq/rnn/embedding_wrapper/embedding"], use_locking=true, validate_shape=true                                                                                                                     , _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_rnn_seq2seq/rnn/emb                                                                                                                     edding_wrapper/embedding, save/RestoreV2_7)]]
         [[Node: save/RestoreV2_4/_11 = _Recv[client_terminated=false, recv_devi                                                                                                                     ce="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:                                                                                                                     0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_45_save/RestoreV2_                                                                                                                     4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by Conchylicultor** [comment]
Did you also copy the `config.ini` file in the `model-server` directory ? Your problem seems to be a mismatch of vocabulary (from the one on which your model has been trained and the one loaded by the server)

**Comment by Conchylicultor** [comment]
Yes, because if the chatbot don't find the config file, the program assume that the network has been trained with the defaults parameters. That should not be the expected behavior, I'll modify the program so that it raise an warning if the `.ini` file is not present.

**Comment by alanbekker** [comment]
thanks!
