### ISSUE TITLE
crash at tf.scaler_summary()

### ISSUE THREAD

**Issue by gururise** [Conchylicultor/DeepQA#8]
Whenever I try to use the GPU, I get this error:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
Initialize variables...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 972, in _do_call
    return fn(*args)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 954, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'ScalarSummary': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScalarSummary = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](ScalarSummary/tags, sequence_loss/truediv)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/gene/Downloads/DeepQA/chatbot/chatbot.py", line 174, in main
    self.sess.run(tf.initialize_all_variables())
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'ScalarSummary': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScalarSummary = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](ScalarSummary/tags, sequence_loss/truediv)]]

Caused by op 'ScalarSummary', defined at:
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/gene/Downloads/DeepQA/chatbot/chatbot.py", line 158, in main
    self.model = Model(self.args, self.textData)
  File "/home/gene/Downloads/DeepQA/chatbot/model.py", line 58, in __init__
    self.buildNetwork()
  File "/home/gene/Downloads/DeepQA/chatbot/model.py", line 106, in buildNetwork
    tf.scalar_summary('loss', self.lossFct)  # Keep track of the cost
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/logging_ops.py", line 296, in scalar_summary
    val = gen_logging_ops._scalar_summary(tags=tags, values=values, name=scope)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 279, in _scalar_summary
    name=name)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
    op_def=op_def)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2388, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1300, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device to node 'ScalarSummary': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScalarSummary = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](ScalarSummary/tags, sequence_loss/truediv)]]

```

**Comment by Conchylicultor** [comment]
What do you mean by "Whenever I try to use the GPU", if detected, the gpu should be used by default. You shouldn't have to use the --device flag except if you wan't to force CPU.

**Comment by gururise** [comment]
ah, i believe that was the problem. I was running:
python3 main.py --device=gpu

which resulted in the above crash.

Running w/o the --device flag does default to the GPU and does not crash.
Thanks!
